In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## Sentences
sent=["the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "I am a good developer",
      "understand the meaning of words",
      "your videos are good"]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## One Hot Representation
one_hot_rep=[one_hot(words,voc_size) for words in sent]
one_hot_rep

[[4795, 5336, 1645, 6936],
 [4795, 5336, 1645, 3187],
 [4795, 2822, 1645, 8567],
 [2461, 6081, 2998, 5956, 5436],
 [2461, 6081, 2998, 5956, 646],
 [671, 4795, 1424, 1645, 18],
 [6031, 2440, 3040, 5956]]

In [8]:
## Word embedding representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4795 5336 1645 6936]
 [   0    0    0    0 4795 5336 1645 3187]
 [   0    0    0    0 4795 2822 1645 8567]
 [   0    0    0 2461 6081 2998 5956 5436]
 [   0    0    0 2461 6081 2998 5956  646]
 [   0    0    0  671 4795 1424 1645   18]
 [   0    0    0    0 6031 2440 3040 5956]]


In [11]:
## feature representation
dim=10

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile("adam","mse") ## for training

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 380ms/step


array([[[-0.00051282,  0.01280215,  0.01626318,  0.01035926,
         -0.04137752, -0.01136701,  0.01788021,  0.02940489,
         -0.03402165, -0.04337817],
        [-0.00051282,  0.01280215,  0.01626318,  0.01035926,
         -0.04137752, -0.01136701,  0.01788021,  0.02940489,
         -0.03402165, -0.04337817],
        [-0.00051282,  0.01280215,  0.01626318,  0.01035926,
         -0.04137752, -0.01136701,  0.01788021,  0.02940489,
         -0.03402165, -0.04337817],
        [-0.00051282,  0.01280215,  0.01626318,  0.01035926,
         -0.04137752, -0.01136701,  0.01788021,  0.02940489,
         -0.03402165, -0.04337817],
        [-0.04047246,  0.03786391, -0.02739054,  0.00785076,
         -0.03462633, -0.00407008,  0.02551936, -0.03616831,
          0.0134684 ,  0.03575703],
        [-0.01770282, -0.04623119, -0.00524666,  0.03941793,
          0.01559395, -0.00513598, -0.02823534,  0.04476062,
          0.00231925, -0.04339036],
        [-0.03755896,  0.03312181,  0.03873936,  0.0